### PR TITLE
reconciler timezone bug

### LINKED ISSUE #20: reconciler prompts on same day due to UTC timezone bug

### PR DESCRIPTION
**Pull request by jamesfulford**
Fixes #20

### CODE REVIEW

File: src/pages/plan/parameters/Reconciler.tsx [hunk 1]
```diff
@@ -15,7 +15,10 @@ export const Reconciler = ({
   // eslint-disable-next-line @typescript-eslint/no-explicit-any
   setParameters: (params: Partial<IParameters>) => Promise<any>;
 }) => {
-  const now = new Date().toISOString().split("T")[0];
```
Comment (jamesfulford) [inline src/pages/plan/parameters/Reconciler.tsx:18]: `toISOString()` expresses the date in UTC time (ends with Z)
