### PR TITLE
fix: tooltip input groups can be clicked on anywhere in input group

### LINKED ISSUE #27: Tooltip (button group) click only applies to icon; should be whole button

### PR DESCRIPTION
**Pull request by jamesfulford**
Fixes #27

### CODE REVIEW

File: src/pages/plan/transactions/TransactionsContainer.tsx [hunk 1]
```diff
@@ -2,10 +2,10 @@ import { Transaction } from "./Transaction";
 import { IApiTransaction } from "../../../services/TransactionsService";
 import Table from "react-bootstrap/esm/Table";
 
-export function limitShownTransactions(
+function limitShownTransactions(
   transactions: IApiTransaction[],
 ): IApiTransaction[] {
-  return transactions.slice(0, 200);
```
Comment (jamesfulford) [inline src/pages/plan/transactions/TransactionsContainer.tsx:8]: Avoiding this bug later; table virtualization added to backlog.
